version: "3"
services:
  plotly-with-jupyter:
    restart: always
    build: .
    container_name: "plotly-with-jupyter"
    tty: true
    privileged: true
    volumes:
      - ./notebooks:/work/notebooks
    command: jupyter-lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --notebook-dir=/work
    ports:
      - "8888:8888"
